### ISSUE TITLE
Add Github Action for CI

### ISSUE THREAD

**Issue by devjorgecastro** [devjorgecastro/yape-android-test#24]
The following initial configuration is added for the CI:

```yaml
name: Check Code Base

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: General Setup
        run: |
          chmod +x ./gradlew

      - name: Create local.properties
        run: |
          echo "MAP_API_KEY=${{ secrets.MAP_API_KEY }}" > local.properties
          echo "SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}" >> local.properties
          echo "SONAR_LOGIN=${{ secrets.SONAR_LOGIN }}" >> local.properties
          echo "SONAR_PROJECT_KEY=${{ secrets.SONAR_PROJECT_KEY }}" >> local.properties

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Sonarqube Report
        run: ./gradlew sonar -Dsonar.login="${{ secrets.SONAR_LOGIN }}"

```
